create table if not exists songs (
song_id integer primary key generated by default as identity,
  song_name varchar(100) not null default 'no song title',
  album_name varchar(100) not null default 'no album title',
  artist integer references artists(artist_id) not null
)